package com.qlazy.tmall.entity;

import java.util.Date;

public class order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.id
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.orderCode
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private String ordercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.address
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.post
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private String post;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.receiver
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private String receiver;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.mobile
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.userMessage
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private String usermessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.createDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.payDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private Date paydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.deliveryDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private Date deliverydate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.confirmDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private Date confirmdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.uid
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_.status
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.id
     *
     * @return the value of order_.id
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.id
     *
     * @param id the value for order_.id
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.orderCode
     *
     * @return the value of order_.orderCode
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public String getOrdercode() {
        return ordercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.orderCode
     *
     * @param ordercode the value for order_.orderCode
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setOrdercode(String ordercode) {
        this.ordercode = ordercode == null ? null : ordercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.address
     *
     * @return the value of order_.address
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.address
     *
     * @param address the value for order_.address
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.post
     *
     * @return the value of order_.post
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.post
     *
     * @param post the value for order_.post
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.receiver
     *
     * @return the value of order_.receiver
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public String getReceiver() {
        return receiver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.receiver
     *
     * @param receiver the value for order_.receiver
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setReceiver(String receiver) {
        this.receiver = receiver == null ? null : receiver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.mobile
     *
     * @return the value of order_.mobile
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.mobile
     *
     * @param mobile the value for order_.mobile
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.userMessage
     *
     * @return the value of order_.userMessage
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public String getUsermessage() {
        return usermessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.userMessage
     *
     * @param usermessage the value for order_.userMessage
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setUsermessage(String usermessage) {
        this.usermessage = usermessage == null ? null : usermessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.createDate
     *
     * @return the value of order_.createDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.createDate
     *
     * @param createdate the value for order_.createDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.payDate
     *
     * @return the value of order_.payDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public Date getPaydate() {
        return paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.payDate
     *
     * @param paydate the value for order_.payDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setPaydate(Date paydate) {
        this.paydate = paydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.deliveryDate
     *
     * @return the value of order_.deliveryDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public Date getDeliverydate() {
        return deliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.deliveryDate
     *
     * @param deliverydate the value for order_.deliveryDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.confirmDate
     *
     * @return the value of order_.confirmDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public Date getConfirmdate() {
        return confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.confirmDate
     *
     * @param confirmdate the value for order_.confirmDate
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setConfirmdate(Date confirmdate) {
        this.confirmdate = confirmdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.uid
     *
     * @return the value of order_.uid
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.uid
     *
     * @param uid the value for order_.uid
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_.status
     *
     * @return the value of order_.status
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_.status
     *
     * @param status the value for order_.status
     *
     * @mbg.generated Wed Nov 13 09:08:46 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}