package com.qlazy.tmall.entity;

import java.util.Date;

public class product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.name
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.subTitle
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private String subtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.originalPrice
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private Float originalprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.promotePrice
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private Float promoteprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.stock
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private Integer stock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.cid
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private Integer cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.createDate
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id
     *
     * @return the value of product.id
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id
     *
     * @param id the value for product.id
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.name
     *
     * @return the value of product.name
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.name
     *
     * @param name the value for product.name
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.subTitle
     *
     * @return the value of product.subTitle
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public String getSubtitle() {
        return subtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.subTitle
     *
     * @param subtitle the value for product.subTitle
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setSubtitle(String subtitle) {
        this.subtitle = subtitle == null ? null : subtitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.originalPrice
     *
     * @return the value of product.originalPrice
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public Float getOriginalprice() {
        return originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.originalPrice
     *
     * @param originalprice the value for product.originalPrice
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setOriginalprice(Float originalprice) {
        this.originalprice = originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.promotePrice
     *
     * @return the value of product.promotePrice
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public Float getPromoteprice() {
        return promoteprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.promotePrice
     *
     * @param promoteprice the value for product.promotePrice
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setPromoteprice(Float promoteprice) {
        this.promoteprice = promoteprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.stock
     *
     * @return the value of product.stock
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public Integer getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.stock
     *
     * @param stock the value for product.stock
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setStock(Integer stock) {
        this.stock = stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.cid
     *
     * @return the value of product.cid
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public Integer getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.cid
     *
     * @param cid the value for product.cid
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setCid(Integer cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.createDate
     *
     * @return the value of product.createDate
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.createDate
     *
     * @param createdate the value for product.createDate
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}