package com.qlazy.tmall.entity;

import org.springframework.stereotype.Component;

@Component
public class productImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.id
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.pid
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column productimage.type
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.id
     *
     * @return the value of productimage.id
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.id
     *
     * @param id the value for productimage.id
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.pid
     *
     * @return the value of productimage.pid
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.pid
     *
     * @param pid the value for productimage.pid
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column productimage.type
     *
     * @return the value of productimage.type
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column productimage.type
     *
     * @param type the value for productimage.type
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}