package com.qlazy.tmall.entity;

import org.springframework.stereotype.Component;

@Component
public class propertyvalue {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propertyvalue.id
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propertyvalue.pid
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propertyvalue.ptid
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private Integer ptid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column propertyvalue.value
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    private String value;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propertyvalue.id
     *
     * @return the value of propertyvalue.id
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propertyvalue.id
     *
     * @param id the value for propertyvalue.id
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propertyvalue.pid
     *
     * @return the value of propertyvalue.pid
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propertyvalue.pid
     *
     * @param pid the value for propertyvalue.pid
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propertyvalue.ptid
     *
     * @return the value of propertyvalue.ptid
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public Integer getPtid() {
        return ptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propertyvalue.ptid
     *
     * @param ptid the value for propertyvalue.ptid
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setPtid(Integer ptid) {
        this.ptid = ptid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column propertyvalue.value
     *
     * @return the value of propertyvalue.value
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column propertyvalue.value
     *
     * @param value the value for propertyvalue.value
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }
}