package com.qlazy.tmall.entity;

import java.util.Date;

public class review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.id
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.content
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.uid
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.pid
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.createDate
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    private Date createdate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.id
     *
     * @return the value of review.id
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.id
     *
     * @param id the value for review.id
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.content
     *
     * @return the value of review.content
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.content
     *
     * @param content the value for review.content
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.uid
     *
     * @return the value of review.uid
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.uid
     *
     * @param uid the value for review.uid
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.pid
     *
     * @return the value of review.pid
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.pid
     *
     * @param pid the value for review.pid
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.createDate
     *
     * @return the value of review.createDate
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.createDate
     *
     * @param createdate the value for review.createDate
     *
     * @mbg.generated Mon Oct 28 20:49:54 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }
}