package com.qlazy.tmall.mapper;

import com.qlazy.tmall.entity.orderitem;
import com.qlazy.tmall.entity.orderitemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface orderitemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    long countByExample(orderitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int deleteByExample(orderitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int insert(orderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int insertSelective(orderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    List<orderitem> selectByExampleWithRowbounds(orderitemExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    List<orderitem> selectByExample(orderitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    orderitem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") orderitem record, @Param("example") orderitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int updateByExample(@Param("record") orderitem record, @Param("example") orderitemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int updateByPrimaryKeySelective(orderitem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orderitem
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int updateByPrimaryKey(orderitem record);
}