package com.qlazy.tmall.mapper;

import com.qlazy.tmall.entity.productImg;
import com.qlazy.tmall.entity.productImgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface productImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    long countByExample(productImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    int deleteByExample(productImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    int insert(productImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    int insertSelective(productImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    List<productImg> selectByExampleWithRowbounds(productImgExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    List<productImg> selectByExample(productImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    productImg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") productImg record, @Param("example") productImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    int updateByExample(@Param("record") productImg record, @Param("example") productImgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    int updateByPrimaryKeySelective(productImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table productimage
     *
     * @mbg.generated Thu Nov 07 10:13:22 CST 2019
     */
    int updateByPrimaryKey(productImg record);
}