package com.qlazy.tmall.mapper;

import com.qlazy.tmall.entity.property;
import com.qlazy.tmall.entity.propertyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface propertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    long countByExample(propertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    int deleteByExample(propertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    int insert(property record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    int insertSelective(property record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    List<property> selectByExampleWithRowbounds(propertyExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    List<property> selectByExample(propertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    property selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    int updateByExampleSelective(@Param("record") property record, @Param("example") propertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    int updateByExample(@Param("record") property record, @Param("example") propertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    int updateByPrimaryKeySelective(property record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table property
     *
     * @mbg.generated Wed Oct 30 09:09:36 CST 2019
     */
    int updateByPrimaryKey(property record);
}