package com.qlazy.tmall.mapper;

import com.qlazy.tmall.entity.propertyvalue;
import com.qlazy.tmall.entity.propertyvalueExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface propertyvalueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    long countByExample(propertyvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int deleteByExample(propertyvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int insert(propertyvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int insertSelective(propertyvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    List<propertyvalue> selectByExampleWithRowbounds(propertyvalueExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    List<propertyvalue> selectByExample(propertyvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    propertyvalue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int updateByExampleSelective(@Param("record") propertyvalue record, @Param("example") propertyvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int updateByExample(@Param("record") propertyvalue record, @Param("example") propertyvalueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int updateByPrimaryKeySelective(propertyvalue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table propertyvalue
     *
     * @mbg.generated Tue Oct 29 16:34:44 CST 2019
     */
    int updateByPrimaryKey(propertyvalue record);
}